### ISSUE TITLE
checkvalue missing

### ISSUE THREAD

**Issue by jcwright77** [eepeterson/pleiades#7]
a checkvalue function and decorator is missing a definition.

**Comment by eepeterson** [comment]
@jcwright77 can you post the use case and error message? I have no import issues right now.

**Comment by jcwright77** [comment]
git pull
python3.6

>>> import pleiades
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jwright/Codes/pleiades/pleiades/__init__.py", line 5, in <module>
    from pleiades.current_sets import *
  File "/Users/jwright/Codes/pleiades/pleiades/current_sets.py", line 11, in <module>
    import pleiades.checkvalue as cv
AttributeError: module 'pleiades' has no attribute 'checkvalue'


Note that there is not definition of checkvalue in the source.
You might have to make a clean checkout incase you have something not checked in.

**Comment by jcwright77** [comment]
fixed by add pleiades to sys.path

**Comment by eepeterson** [comment]
Did you install pleiades in "editable" mode with `pip install -e .` from the top directory of the repo? If you installed a branch without `-e` it won't get the latest updates when you do `git pull` Also, make sure python, python3, and python 3.6 are all referring to the python distribution you think they are. When I did `which python3.6` I got `/usr/bin/python3.6`, but I had only installed pleiades into anaconda in my home directory and `which python3` points to `/home/peterson/pkgs/anaconda3/bin/python3` Therefore the import worked when I ran the `python3` exectuable, but not when I ran `python3.6`

**Comment by jcwright77** [comment]
Issue was just setting path which is necessary when not installing in default path. In this case, I'm running in a colaboratory notebook. Also lazy search for checkvalue does not turn up anything because it is just the name of the file and not a class.
